name: ci

on:
  push:

env:
  image_name_base: hn-stories-worker
  image_tag: ci

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.24"

    - name: Check formatting
      run: |
        if [[ -n $(gofmt -d .) ]]; then
          exit 1
        fi

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test ./...

    - name: Build image
      run: |
        branch=$(git rev-parse --abbrev-ref HEAD)
        commit=$(git rev-parse --short --verify ${branch})
        image_name=${image_name_base}-${branch}
        docker build . --tag=${image_name}:${{ env.image_tag }} --tag=${image_name}:${commit}
